import { defineConfig } from "eslint/config";
import { node } from "@nocido/config/eslint/node";

// Migrations are generated by `medusa db:generate`.
export default defineConfig({ ignores: ["src/**/migrations/**"] }, node);
