import type { ThemePreset } from "./types";

export const bleuConfiance: ThemePreset = {
  id: "bleu-confiance",
  name: { ar: "أزرق الثقة", fr: "Bleu confiance", en: "Trust blue" },
  description: {
    ar: "أزرق واضح ومطمئن.",
    fr: "Bleu franc et rassurant.",
    en: "Clear, reassuring blue.",
  },
  light: {
    bg: "#F5F8FC",
    fg: "#0F1E33",
    card: "#FFFFFF",
    cardFg: "#0F1E33",
    primary: "#1D4ED8",
    primaryFg: "#FFFFFF",
    accent: "#0F766E",
    accentFg: "#FFFFFF",
    muted: "#E8EEF6",
    mutedFg: "#4A5B73",
    border: "#D6E0EC",
    ring: "#1D4ED8",
    success: "#15803D",
    warning: "#9A5B00",
    danger: "#C0262D",
  },
  dark: {
    bg: "#0A1422",
    fg: "#E6EEF8",
    card: "#111E30",
    cardFg: "#E6EEF8",
    primary: "#6EA8FF",
    primaryFg: "#0A1422",
    accent: "#5EEAD4",
    accentFg: "#0A1422",
    muted: "#16243A",
    mutedFg: "#9FB1C8",
    border: "#243752",
    ring: "#6EA8FF",
    success: "#4ADE80",
    warning: "#FACC15",
    danger: "#F87171",
  },
  radius: { base: 8, card: 16, button: 12 },
  fonts: { display: "noto-kufi-arabic", body: "ibm-plex-sans-arabic" },
};
