import type { ThemePreset } from "./types";

export const heritageDore: ThemePreset = {
  id: "heritage-dore",
  name: { ar: "التراث الذهبي", fr: "Héritage doré", en: "Golden heritage" },
  description: {
    ar: "كريمي وبني وذهبي، دافئ وحرفي.",
    fr: "Crème, brun et or. Chaleureux et artisanal.",
    en: "Cream, brown and gold. Warm and artisanal.",
  },
  light: {
    bg: "#F7F1E6",
    fg: "#2B1B0E",
    card: "#FFFBF3",
    cardFg: "#2B1B0E",
    primary: "#E9B44C",
    primaryFg: "#2B1B0E",
    accent: "#8A5A1F",
    accentFg: "#FFFBF3",
    muted: "#EFE5D3",
    mutedFg: "#6B5540",
    border: "#E3D5BD",
    ring: "#A8741F",
    success: "#2A7343",
    warning: "#8F5E00",
    danger: "#B42318",
  },
  dark: {
    bg: "#1A120A",
    fg: "#F5ECDD",
    card: "#241910",
    cardFg: "#F5ECDD",
    primary: "#E9B44C",
    primaryFg: "#2B1B0E",
    accent: "#F0C878",
    accentFg: "#1A120A",
    muted: "#2E2217",
    mutedFg: "#C4B299",
    border: "#3A2C1F",
    ring: "#E9B44C",
    success: "#5CC98A",
    warning: "#F0B94D",
    danger: "#F97066",
  },
  radius: { base: 12, card: 24, button: "pill" },
  fonts: { display: "amiri", body: "ibm-plex-sans-arabic" },
};
