import type { ThemePreset } from "./types";

export const minimalBlanc: ThemePreset = {
  id: "minimal-blanc",
  name: { ar: "أبيض بسيط", fr: "Minimal blanc", en: "Minimal white" },
  description: {
    ar: "أبيض وأسود، نظيف ومباشر.",
    fr: "Noir et blanc. Net et direct.",
    en: "Black and white. Clean and direct.",
  },
  light: {
    bg: "#FFFFFF",
    fg: "#111111",
    card: "#FAFAFA",
    cardFg: "#111111",
    primary: "#111111",
    primaryFg: "#FFFFFF",
    accent: "#3F3F46",
    accentFg: "#FFFFFF",
    muted: "#F4F4F5",
    mutedFg: "#5F5F66",
    border: "#E6E6E6",
    ring: "#111111",
    success: "#15803D",
    warning: "#A15C07",
    danger: "#B91C1C",
  },
  dark: {
    bg: "#0B0B0C",
    fg: "#F5F5F5",
    card: "#151517",
    cardFg: "#F5F5F5",
    primary: "#F5F5F5",
    primaryFg: "#0B0B0C",
    accent: "#D4D4D8",
    accentFg: "#0B0B0C",
    muted: "#1C1C1F",
    mutedFg: "#A1A1AA",
    border: "#2A2A2E",
    ring: "#F5F5F5",
    success: "#4ADE80",
    warning: "#FACC15",
    danger: "#F87171",
  },
  radius: { base: 8, card: 16, button: 10 },
  fonts: { display: "readex-pro", body: "ibm-plex-sans-arabic" },
};
