import type { ThemePreset } from "./types";

export const nuitElegante: ThemePreset = {
  id: "nuit-elegante",
  name: { ar: "ليلة أنيقة", fr: "Nuit élégante", en: "Elegant night" },
  description: {
    ar: "أزرق ليلي مع لمسة شمبانيا.",
    fr: "Bleu nuit et touches champagne.",
    en: "Midnight blue with champagne accents.",
  },
  light: {
    bg: "#F4F2EE",
    fg: "#14172B",
    card: "#FFFFFF",
    cardFg: "#14172B",
    primary: "#1E2447",
    primaryFg: "#F4F2EE",
    accent: "#7F5F22",
    accentFg: "#FFFFFF",
    muted: "#E9E6DF",
    mutedFg: "#555A70",
    border: "#DAD5CA",
    ring: "#1E2447",
    success: "#2E7D4F",
    warning: "#8F5E00",
    danger: "#B3261E",
  },
  dark: {
    bg: "#0E1022",
    fg: "#ECE8DF",
    card: "#171A33",
    cardFg: "#ECE8DF",
    primary: "#C8A96A",
    primaryFg: "#0E1022",
    accent: "#AFB6FF",
    accentFg: "#0E1022",
    muted: "#1C2040",
    mutedFg: "#A9ABC2",
    border: "#2B3057",
    ring: "#C8A96A",
    success: "#63C58A",
    warning: "#E7C069",
    danger: "#F28B82",
  },
  radius: { base: 10, card: 20, button: "pill" },
  fonts: { display: "el-messiri", body: "ibm-plex-sans-arabic" },
};
