import type { ThemePreset } from "./types";

export const roseDouce: ThemePreset = {
  id: "rose-douce",
  name: { ar: "وردي ناعم", fr: "Rose douce", en: "Soft rose" },
  description: {
    ar: "وردي ناعم وبنفسجي.",
    fr: "Rose tendre et prune.",
    en: "Tender rose and plum.",
  },
  light: {
    bg: "#FFF6F7",
    fg: "#3A1722",
    card: "#FFFFFF",
    cardFg: "#3A1722",
    primary: "#B83B5E",
    primaryFg: "#FFFFFF",
    accent: "#7A3E8E",
    accentFg: "#FFFFFF",
    muted: "#F8E8EB",
    mutedFg: "#74515B",
    border: "#F0D5DB",
    ring: "#B83B5E",
    success: "#2E7D4F",
    warning: "#8F5E00",
    danger: "#B42318",
  },
  dark: {
    bg: "#1C0E13",
    fg: "#F8E9ED",
    card: "#26141B",
    cardFg: "#F8E9ED",
    primary: "#F28FAD",
    primaryFg: "#1C0E13",
    accent: "#D7A8E6",
    accentFg: "#1C0E13",
    muted: "#2E1820",
    mutedFg: "#C9A7B1",
    border: "#432530",
    ring: "#F28FAD",
    success: "#63C58A",
    warning: "#E7C069",
    danger: "#FF8A80",
  },
  radius: { base: 16, card: 28, button: "pill" },
  fonts: { display: "el-messiri", body: "readex-pro" },
};
