import type { ThemePreset } from "./types";

export const terracotta: ThemePreset = {
  id: "terracotta",
  name: { ar: "تيراكوتا", fr: "Terracotta", en: "Terracotta" },
  description: {
    ar: "طين محروق وزيتوني.",
    fr: "Terre cuite et olive.",
    en: "Fired clay and olive.",
  },
  light: {
    bg: "#FAF3EE",
    fg: "#2E1A12",
    card: "#FFFFFF",
    cardFg: "#2E1A12",
    primary: "#A9471F",
    primaryFg: "#FFFFFF",
    accent: "#5E6B3A",
    accentFg: "#FFFFFF",
    muted: "#F1E4DA",
    mutedFg: "#6E5144",
    border: "#E8D5C7",
    ring: "#A9471F",
    success: "#2F7D4A",
    warning: "#8F5E00",
    danger: "#A8201A",
  },
  dark: {
    bg: "#1B110C",
    fg: "#F5E8DF",
    card: "#251812",
    cardFg: "#F5E8DF",
    primary: "#E38B5E",
    primaryFg: "#1B110C",
    accent: "#B9C98A",
    accentFg: "#1B110C",
    muted: "#2D1E16",
    mutedFg: "#C7AB9C",
    border: "#3F2A1F",
    ring: "#E38B5E",
    success: "#6BCB8B",
    warning: "#EBC066",
    danger: "#FF8A7A",
  },
  radius: { base: 10, card: 22, button: "pill" },
  fonts: { display: "amiri", body: "noto-naskh-arabic" },
};
