import type { ThemePreset } from "./types";

export const vertNature: ThemePreset = {
  id: "vert-nature",
  name: { ar: "أخضر طبيعي", fr: "Vert nature", en: "Nature green" },
  description: {
    ar: "أخضر نباتي وتفاصيل مغرة.",
    fr: "Vert végétal et détails ocre.",
    en: "Leafy green with ochre details.",
  },
  light: {
    bg: "#F3F6EF",
    fg: "#1C2B1E",
    card: "#FFFFFF",
    cardFg: "#1C2B1E",
    primary: "#2F6B3A",
    primaryFg: "#FFFFFF",
    accent: "#7A5A00",
    accentFg: "#FFFFFF",
    muted: "#E6ECDF",
    mutedFg: "#4F6152",
    border: "#D5DFCC",
    ring: "#2F6B3A",
    success: "#2F6B3A",
    warning: "#865A00",
    danger: "#B42318",
  },
  dark: {
    bg: "#0F1A11",
    fg: "#E7EFE3",
    card: "#172419",
    cardFg: "#E7EFE3",
    primary: "#7BC48A",
    primaryFg: "#0F1A11",
    accent: "#D9B84A",
    accentFg: "#0F1A11",
    muted: "#1E2E21",
    mutedFg: "#A7B9A9",
    border: "#2A3D2D",
    ring: "#7BC48A",
    success: "#7BC48A",
    warning: "#E5C15A",
    danger: "#F28B82",
  },
  radius: { base: 14, card: 28, button: "pill" },
  fonts: { display: "reem-kufi", body: "noto-kufi-arabic" },
};
